name: 'Webex Message Action'
description: 'Sends a message to Cisco Webex'
inputs:
  webex-token:
    description: 'Webex Bot or User Token'
    required: true
  room-id:
    description: 'Webex Room ID to send message to'
    required: true
  message:
    description: 'Message to send'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'message-square'
  color: 'blue' 